### ISSUE TITLE
Error when compiling cc.c using ccself; cc.c:719: error: expected ')', found '�'

### ISSUE THREAD

**Issue by mewmew** [Fedjmike/mini-c#3]
The selftest test case passes just fine. However, when trying to compile cc.c using the `ccself` binary, it fails with the following errors.

```bash
u@x220 ~/D/c/c/mini-c> make selftest
gcc -m32 -std=gnu11 -Werror -Wall cc.c -o cc
./cc cc.c
gcc -m32 a.s -o ccself
./ccself tests/triangular.c
gcc -m32 a.s -o triangular; ./triangular 5; [ $? -eq 15 ]
u@x220 ~/D/c/c/mini-c> ./ccself cc.c
cc.c:719: error: expected ')', found '�'
cc.c:719: error: expected ';', found '�'
cc.c:719: error: expected '}', found '�'
```

Note, compiling cc.c with the produced `cc` binary works just fine, and compiling triangular.c with `ccself` also works just fine.

Is `ccself` intended to be able to compile cc.c?

**Comment by Fedjmike** [comment]
Thanks for the bug report! Yes, this is intended to work. Which version/branch of mini-c are you using? I notice it says line 719 in the output, even though the latest version only has 700 lines. Could you give me your `uname -a` and `gcc -v`?

What's with the question mark symbol in your output? Does that appear on your console too? Is there some way you can switch your terminal emulator or something to get that to appear correctly? Try piping the output to a file and opening it an another editor (or a byte editor). It's probably just 0x00 though. In fact you could simply edit the line in mini-c itself to print the character as an integer instead.

**Comment by mewmew** [comment]
I'm using revision bb06b26162b76fefbde9be309e17c79cdc773c7e of mini-c.

```
u@x220 ~> uname -a
Linux x220 4.10.4-1-ARCH #1 SMP PREEMPT Sat Mar 18 19:39:18 CET 2017 x86_64 GNU/Linux
u@x220 ~> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.3.1 20170306 (GCC) 
```

> What's with the question mark symbol in your output? Does that appear on your console too?

They do indeed appear in my console. I reckon they are the UTF-8 replacement character; https://godoc.org/unicode#ReplacementChar

> Is there some way you can switch your terminal emulator or something to get that to appear correctly?

I tried both [lwt](https://github.com/mewkiz/lwt) and xterm. Both give the same results.

```
u@x220 ~/D/c/c/mini-c> ./ccself cc.c > foo.txt
u@x220 ~/D/c/c/mini-c> hexdump -C foo.txt
00000000  63 63 2e 63 3a 37 31 39  3a 20 65 72 72 6f 72 3a  |cc.c:719: error:|
00000010  20 65 78 70 65 63 74 65  64 20 27 29 27 2c 20 66  | expected ')', f|
00000020  6f 75 6e 64 20 27 ff 27  0a 63 63 2e 63 3a 37 31  |ound '.'.cc.c:71|
00000030  39 3a 20 65 72 72 6f 72  3a 20 65 78 70 65 63 74  |9: error: expect|
00000040  65 64 20 27 3b 27 2c 20  66 6f 75 6e 64 20 27 ff  |ed ';', found '.|
00000050  27 0a 63 63 2e 63 3a 37  31 39 3a 20 65 72 72 6f  |'.cc.c:719: erro|
00000060  72 3a 20 65 78 70 65 63  74 65 64 20 27 7d 27 2c  |r: expected '}',|
00000070  20 66 6f 75 6e 64 20 27  ff 27 0a                 | found '.'.|
0000007b
```

They correspond to hexadecimal 0xFF.

**Comment by mewmew** [comment]
@Fedjmike Have you been able to reproduce the error? If not, let me know how I may assist you in debugging the issue.

**Comment by Fedjmike** [comment]
I reproduced it and found and fixed two bugs. Thanks for the report and good luck with the decompiler!

**Comment by mewmew** [comment]
> I reproduced it and found and fixed two bugs. Thanks for the report and good luck with the decompiler!

Thanks!

Have a lovely weekend : )

**Comment by mewmew** [comment]
Oh lovely!

```
u@x220 ~/D/c/c/mini-c> make ccself
gcc -m32 -std=gnu11 -Werror -Wall cc.c -o cc
./cc cc.c
gcc -m32 a.s -o ccself
u@x220 ~/D/c/c/mini-c> mv a.s orig.s
u@x220 ~/D/c/c/mini-c> ./ccself cc.c
u@x220 ~/D/c/c/mini-c> sha1sum orig.s a.s
d9b8ca6f7a00c4023c2942f9407c3dcf16a42f10  orig.s
d9b8ca6f7a00c4023c2942f9407c3dcf16a42f10  a.s
```

The assembly output is indeed identical!

Thanks Sam for developing mini-c. Will have fun trying to produce byte identical output using the decompiler : )

Cheers /u

**Comment by Fedjmike** [comment]
Great. I'd be interested to see what the decompiled Go looks like - I'd be impressed if you manage to deal with the rather sadistically obfuscated code that mini-c produces for function calls.

**Comment by mewmew** [comment]
> Great. I'd be interested to see what the decompiled Go looks like - I'd be impressed if you manage to deal with the rather sadistically obfuscated code that mini-c produces for function calls.

Haha, yes. Will be a fun challenge. We'll report back when the decompiler has reached some maturity with regards to decompiling mini-c.
